[package]
name = "nabu"
version = "3.0.0"
edition = "2024"
rust-version = "1.93.0"

[dependencies]
athena = { git = "https://github.com/Xqhare/athena", features = ["encoding_decoding", "checksum", "byte_bit"] }

[dev-dependencies]
tyche = { git = "https://github.com/Xqhare/tyche" }

[patch."https://github.com/Xqhare/athena"]
athena = { path = "../athena" }

[patch."https://github.com/xqhare/athena.git"]
athena = { path = "../athena" }

[patch."https://github.com/Xqhare/aequa"]
aequa = { path = "../aequa" }

[patch."https://github.com/xqhare/aequa.git"]
aequa = { path = "../aequa" }

[patch."https://github.com/Xqhare/tyche"]
tyche = { path = "../tyche" }

