[package]
name = "nabu"
version = "1.2.1"
edition = "2021"

[dependencies]

[dev-dependencies]
tyche = { git = "https://github.com/Xqhare/tyche" }

[features]
key_value_core = []
key_value_store = ["key_value_core"]
logging_wizard = []

[package.metadata.docs.rs]
all-features = true
