[package]
name = "nabu"
version = "1.1.1"
edition = "2021"

[dependencies]

[dev-dependencies]
tyche = { git = "https://github.com/Xqhare/tyche" }

[features]
key_value_core = []
key_value_store = ["key_value_core"]
config_wizard = []
logging_wizard = []
